version: '3.2'
services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paises_api
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"


volumes:
  mysql:

